DESC felhasznalok;
DESC gyartok;
DESC termekek;
DESC megrendelesek;
SELECT TABLE_NAME AS "Tábla neve" CONSTRAINT_NAME AS "Megszorítás neve", CONSTRAINT_TYPE AS "Megszorítás típusa" FROM USER_CONSTRAINTS WHERE UPPER(TABLE_NAME) IN ('FELHASZNALOK', 'GYARTOK', 'TERMEKEK', 'MEGRENDELESEK') AND UPPER(CONSTRAINT_NAME) NOT LIKE '%SYS%';

PROMPT --==  ==--;
PROMPT;
PROMPT;
PROMPT --== Felhasználók tábla ==--;
CLEAR COLUMNS;
COLUMN felhasznaloi_nev FORMAT A15 HEADING 'Felhasználói|név';
COLUMN felhasznaloi_jelszo FORMAT A15 HEADING 'Felhasználói|jelszó';
COLUMN felhasznalo_neve FORMAT A15 HEADING 'Felhasználó|neve';
COLUMN felhasznalo_iranyitoszama FORMAT 9999 HEADING 'Felhasználó|irányítószáma';
COLUMN felhasznalo_telefonszama FORMAT 999999999 HEADING 'Felhasználó|telefonszáma';
COLUMN felhasznaloi_email_cime FORMAT A25 HEADING 'Felhasználó|e-mail címe';
COLUMN felhasznaloi_neme FORMAT A5 HEADING 'Felhasználó|neme';
COLUMN felhasznalo_szuletesi_ideje HEADING 'Felhasználó|születési ideje';
COLUMN regisztracio_ideje HEADING 'Regisztráció|ideje';
SET PAGESIZE 30;
SET LINESIZE 150;
SELECT * FROM felhasznalok;
PROMPT;
PROMPT --== Gyártók tábla ==--;
CLEAR COLUMNS;
COLUMN gyarto_neve FORMAT A15 HEADING 'Cég|neve';
COLUMN ceg_tipusa FORMAT A3 HEADING 'Cég|típusa';
COLUMN ceg_alapitasa HEADING 'Cég|alapítása';
COLUMN ceg_iranyitoszama FORMAT 99999 HEADING 'Cég|irányítószáma';
COLUMN ceg_cime FORMAT A30 HEADING 'Cég|címe';
COLUMN ceg_vezetoje FORMAT A20 HEADING 'Cég|vezetõje';
COLUMN ceg_honlapja FORMAT A25 HEADING 'Cég|honlapja';
COLUMN ceg_email_cime FORMAT A25 HEADING 'Cég|e-mail címe';
COLUMN ceg_telefonszama FORMAT 999999999 HEADING 'Cég|telefonszáma';
SET PAGESIZE 30;
SET LINESIZE 150;
SELECT * FROM gyartok;
PROMPT;
PROMPT --== Termékek tábla ==--;
CLEAR COLUMNS;
COLUMN termek_azonosito FORMAT 99 HEADING 'Termék|azonosító';
COLUMN termek_neve FORMAT A15 HEADING 'Termék|neve';
COLUMN gyarto_neve FORMAT A15 HEADING 'Cég|neve';
COLUMN termek_egysegara FORMAT 99999 HEADING 'Termék|egységára';
COLUMN termek_tipusa FORMAT A15 HEADING 'Termék|típusa';
COLUMN gyartasi_ido HEADING 'Gyártási|idõ';
COLUMN raktaron_darabszam FORMAT 99 HEADING 'Raktáron|darabszám';
COLUMN termek_leirasa FORMAT A100 HEADING 'Termék|leírása';
SET PAGESIZE 30;
SET LINESIZE 150;
SELECT * FROM termekek;
PROMPT;
PROMPT --== Megrendelések tábla ==--;
CLEAR COLUMNS;
COLUMN rendelesi_azonosito FORMAT 99 HEADING 'Rendelési|azonosító';
COLUMN rendelesi_szam FORMAT 99 HEADING 'Rendelési|szám';
COLUMN fizetes_modja FORMAT A20 HEADING 'Fizetés|módja';
COLUMN megrendeles_ideje HEADING 'Megrendelés|ideje';
COLUMN atvetel_futarral FORMAT A4 HEADING 'Átvétel|futárral';
COLUMN vegso_ar FORMAT 9999999999 HEADING 'Végsõ|ár';
COLUMN rendelt_darabszam FORMAT 99 HEADING 'Rendelt|darabszám';
COLUMN felhasznaloi_nev FORMAT A15 HEADING 'Felhasználói|név';
COLUMN felhasznaloi_jelszo FORMAT A15 HEADING 'Felhasználói|jelszó';
COLUMN termek_azonosito FORMAT 99 HEADING 'Termék|azonosító';
SET PAGESIZE 30;
SET LINESIZE 150;
SELECT * FROM megrendelesek;